language: rust
sudo: false
cache: cargo
dist: trusty
rust:
  - nightly
os:
  - linux
env:
  - ARCH=x86_64
notifications:
  email: false
script:
  - cd example
  - cargo rustc --release -- -C passes='sancov' -C llvm-args='-sanitizer-coverage-level=4' -Z sanitizer=address
  - (! ./target/release/example -runs=100000)
  - cd ../example_arbitrary
  - cargo rustc --release -- -C passes='sancov' -C llvm-args='-sanitizer-coverage-level=4' -Z sanitizer=address
  - (! ./target/release/example -runs=10000000)
