language: rust
sudo: false
cache: cargo
dist: trusty
rust:
  - nightly
os:
  - linux
env:
  - ARCH=x86_64
notifications:
  email: false
script:
  - cd example
  - cargo rustc -- -C passes='sancov' -C llvm-args='-sanitizer-coverage-level=3' -Z sanitizer=address
  - (! ./target/debug/example)
