[package]
authors = ["The rust-fuzz Project Developers"]
edition = "2018"
license = "MIT/Apache-2.0/NCSA"
name = "libfuzzer-sys"
readme = "./README.md"
repository = "https://github.com/rust-fuzz/libfuzzer"
version = "0.2.0"

[dependencies]
# arbitrary = "0.3"
arbitrary = { git = "https://github.com/rust-fuzz/arbitrary.git", rev = "8fa099d" }

[build-dependencies]
cc = "1.0"

[features]
arbitrary-derive = ["arbitrary/derive"]
